version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"

  migrate:
    image: migrate/migrate
    env_file: .env
    depends_on:
        - database
    volumes:
      - ./db/migrations:/migrations
    # if migration doesn't need to be applied you may get an error you can ignore on compose up: migrate_1   | error: file does not exist
    command: ["-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?sslmode=disable", "up", "3"]
    links:
      - database

volumes:
  data: